telehash/telehash-c

Makefile
include/ext.h
include/ext_path.h
include/link.h
include/lob.h
include/mesh.h
include/util.h
src/ext/path.c
src/lib/lob.c
src/link.c
src/mesh.c
src/net/tcp4.c
src/net/udp4.c
src/util/util.c
test/Makefile
test/ext_path.c
test/interop.sh
test/lib_util.c
test/mesh_core.c
test/net_link.c
test/net_udp4.c
util/ping.c
util/router.c

path support

---

src/lib/base32.c
src/link.c
test/Makefile
test/net_handshake.c

for buffer overflow and link_sync() when handshake again

---

Makefile
include/ext.h
include/ext_peer.h
include/js0n.h
include/link.h
include/mesh.h
include/pipe.h
src/ext/peer.c
src/lib/js0n.c
src/link.c
src/mesh.c
test/Makefile
test/ext_block.c
test/ext_path.c
test/ext_peer.c
test/ext_stream.c
test/net_handshake.c
test/net_loopback.c

Add peer/connect routing support

---

src/e3x/cs1a/aes.c
src/e3x/cs1a/aes128.c
src/e3x/cs1a/aes128.h
src/e3x/cs1a/sha256.c
src/e3x/cs1a/sha256.h

Update crypto dependencies for cs1a

---

include/tmesh.h
src/tmesh/epoch.c
src/tmesh/tmesh.c
test/tmesh_core.c
test/tmesh_device.c
test/tmesh_epoch.c

Iterative progress as it's being real-world tested...

TMesh Updates

---

src/e3x/channel.c
src/e3x/cs1a/cs1a.c
src/ext/peer.c
src/ext/stream.c
src/lib/lob.c
src/link.c
src/net/loopback.c
src/net/tcp4.c
src/net/udp4.c
src/unix/util.c
src/util/chunks.c
src/util/uri.c
src/util/util.c

first pass through all of em, closes #56

Coverity Scan Fixes

---

include/tmesh.h
src/tmesh/tmesh.c
test/tmesh_core.c

Bringing the reference implementation up to match the draft spec

TMesh bugfixes

---

include/tmesh.h
src/tmesh/tmesh.c
test/tmesh_core.c

WIP, simpler ping/pong sync logic

TMesh Minor Updates

---

include/link.h
include/mesh.h
src/ext/peer.c
src/link.c
src/mesh.c
test/mem_last.txt

Improve the internal routing logic by moving away from the hashtable string matching to direct link and routing tokens, also supporting raw forwarding now based on peer/connect links.
Closes #89

better routing support

---

src/e3x/exchange.c
src/e3x/self.c
test/e3x_self.c
test/mem_last.c
test/mem_last.txt

correct some wasted memory from caching strings

cached string cleanup

---

include/tmesh.h
src/lib/lob.c
src/tmesh/tmesh.c
test/Makefile
test/mem_last.txt
test/tmesh_core.c
test/tmesh_device.c

Reworked the timing logic (yet again) to be strictly cycle based (one tick of a 32kHz crystal, 1 / 2^15 of a second, or 32 mibroseconds in binary prefix (1024^-2)), and other experience-based improvements.

TMesh Usability

---

include/mesh.h
include/tmesh.h
src/ext/peer.c
src/link.c
src/mesh.c
src/tmesh/tmesh.c
test/Makefile
test/mem_last.txt
test/net_loopback.c
test/tmesh_core.c
test/tmesh_device.c

1:1 relationship between motes and links, w/ dedicated pre-link and public beacon motes instead of overlapping/mixed states.
Mediums are also now part of and managed by a community directly, not by the radio.

TMesh Simpler

---

include/tmesh.h
include/util_chunks.h
src/ext/peer.c
src/lib/lob.c
src/mesh.c
src/tmesh/tmesh.c
src/util/chunks.c
test/Makefile
test/ext_peer.c
test/mem_last.txt

This is a bunch of changes to get a stable working link running well, it is only an intermediate step and needs serious refactoring next.

TMesh Intermediate

---

include/util_sys.h
src/mesh.c
src/unix/util_sys.c
test/Makefile
test/unit_test.h

Syslog-like levels for logging.
Larger changes to existing `LOG()` calls will have to wait until other branches are merged to reduce git conflicts.

Logging Levels

---

include/util_frames.h
include/util_sys.h
src/tmesh/tmesh.c
src/util/frames.c
test/lib_frames.c

The model for using frames was missing some fidelity around managing the different states, this improves that and brings along some impacted code in the process.

Frames State Improvements

---

src/lib/jwt.c

I'm pretty sure you only need one telehash.h :)

Removes redundant includes

---

include/hashname.h
include/tmesh.h
include/util_sys.h
src/lib/hashname.c
src/link.c
src/mesh.c
src/tmesh/tmesh.c
src/util/frames.c
test/mem_last.txt
test/tmesh_core.c

Many improvements to the new-improved tmesh style signal/stream patterns, including basic abilities to route/forward packets between motes.

Enabling TMesh Routing

---

include/tmesh.h
src/tmesh/tmesh.c
test/mem_last.txt

Improve the state logic around beaconing to follow normal signalling patterns.

Beacon Better

---

Makefile
include/gossip.h
include/telehash.h
src/gossip.c
test/Makefile
test/gossip_core.c

Just the bare structure to start.

Mesh Gossip Utility Basics

---

include/gossip.h

…generated telehash.h does not compile as a result

gossip.h lacks newline at the end of file
